name: phpspec

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    matrix:
      php: [7.1, 7.2, 7.3]
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Composer dependencies
      run: composer install --prefer-dist
    - name: Run tests
      run: php7.1 vendor/bin/phpspec run
